export enum AuthActionTypes {
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  REGISTER_ACCOUNT_SUCCESS_OR_ERROR = 'REGISTER_ACCOUNT_SUCCESS_OR_ERROR',
  REGISTER_ACCOUNT_ERROR = 'REGISTER_ACCOUNT_ERROR',
  LOGIN_SUCCESS_OR_ERROR = 'LOGIN_SUCCESS_OR_ERROR',
  LOGIN_ERROR = 'LOGIN_ERROR',
  SET_USER = 'SET_USER',
}
