export enum LoadingActionTypes {
  REGISTER_LOADING = 'REGISTER_LOADING',
  LOGIN_LOADING = 'LOGIN_LOADING',
  GET_ME_LOADING = 'GET_ME_LOADING',
  CREATE_TASK_LOADING = 'CREATE_TASK_LOADING',
  GET_TASKS_LOADING = 'GET_TASKS_LOADING',
  UPDATE_TASK_LOADING = 'UPDATE_TASK_LOADING',
}
