export enum TaskActionTypes {
  SET_TASKS = 'SET_TASKS',
  CREATE_TASK = 'CREATE_TASK',
  CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS',
  GET_TASKS = 'GET_TASKS',
  UPDATE_TASK = 'UPDATE_TASK',
  DELETE_TASK = 'DELETE_TASK',
  SET_TASK_TO_EDIT = 'SET_TASK_TO_EDIT',
}
